config/routes.rb
Rails.application.routes.draw do
  resources :genres
  resources :users
  resources :movies
  devise_for :users,
             path: "auth",
             path_names: {
               sign_in: "login",
               sign_out: "logout",
               sign_up: "register",
             }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "movies#index"
end

app/models/genre.rb
class Genre < ApplicationRecord
  paginates_per 10

  has_and_belongs_to_many :movies

  validates_presence_of :name
  validates_uniqueness_of :name, allow_blank: true, case_sensitive: false

  scope :with_filter, ->(search) { where("name like ?", "%#{search}%") if search.present? }
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :authenticate_user!
  before_action :set_genre, only: %i[ show edit update destroy ]

  # GET /genres or /genres.json
  def index
    @genres = Genre.with_filter(params[:search])
      .order(id: :desc).page params[:page]
  end

  # GET /genres/1 or /genres/1.json
  def show
  end

  # GET /genres/new
  def new
    @genre = Genre.new
  end

  # GET /genres/1/edit
  def edit
  end

  # POST /genres or /genres.json
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to genres_url, notice: "Genre was successfully created." }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1 or /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to genres_url, notice: "Genre was successfully updated." }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1 or /genres/1.json
  def destroy
    @genre.destroy

    respond_to do |format|
      format.html { redirect_to genres_url, notice: "Genre was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_genre
    @genre = Genre.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_form.html.erb
<%= form_with(model: genre, class: "contents") do |form| %>
  <% if genre.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(genre.errors.count, "error") %> prohibited this genre from being saved:</h2>
    </div>
  <% end %>
  <div class="my-5">
    <%= form.label :name, class: "after:content-['*'] after:ml-1 after:text-red-500 block" %>
    <%= form.text_field :name, class: "mt-2 w-full bg-zinc-700 py-2 px-3 rounded-lg focus:ring-white focus:border-white",
                            placeholder: "Enter name" %>
    <% genre.errors.full_messages_for(:name).each do |message| %>
      <div class="text-red-500 mt-2"><%= message %></div>
    <% end %>
  </div>
  <div class="w-full flex justify-end mt-5">
    <%= link_to "Cancel", genres_path,
                  class: "py-2 px-3 bg-zinc-700 hover:bg-zinc-600 text-white rounded-lg mr-2" %>
    <%= form.submit(params[:action] == "new" ? "Create" : "Update", class: "cursor-pointer py-2 px-3 bg-blue-500 hover:bg-blue-600 text-white rounded-lg") %>
  </div>
<% end %>

app/views/genres/_genre.html.erb
<div id="<%= dom_id genre %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= genre.name %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this genre", genre, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this genre", edit_genre_path(genre), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/genres/_table.html.erb
<table class="min-w-full">
  <thead class="bg-zinc-700 border-b uppercase">
    <tr>
      <th scope="col" class="text-sm font-medium text-white px-6 py-4 text-left">
        ID
      </th>
      <th scope="col" class="text-sm font-medium text-white px-6 py-4 text-left">
        Name
      </th>
      <th scope="col" class="text-sm font-medium text-white px-6 py-4 text-left">
        Created Date
      </th>
      <th scope="col" class="text-sm font-medium text-white px-6 py-4 text-left">
        Actions
      </th>
    </tr>
  </thead>
  <tbody>
    <% @genres.each do |genre| %>
      <tr class="bg-transparent border-b transition duration-300 ease-in-out hover:bg-zinc-800">
        <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-white">
          <%= genre.id %>
        </td>
        <td class="text-sm text-white font-light px-6 py-4 whitespace-nowrap">
          <%= genre.name %>
        </td>
        <td class="text-sm text-white font-light px-6 py-4 whitespace-nowrap">
          <%= Date.parse(genre.created_at.to_s).strftime("%Y-%m-%d") %>
        </td>
        <td class="text-sm text-white font-light px-6 py-4 whitespace-nowrap">
          <%= link_to "Edit", edit_genre_path(genre), class: "px-3 py-2 rounded bg-zinc-700 hover:bg-zinc-600 text-white" %>
          <%= link_to "Delete", genre, data: {
                      turbo_method: :delete,
                      turbo_confirm: "Are you sure?",
                    }, class: "ml-2 px-3 py-2 rounded bg-red-500 hover:bg-red-600 text-white" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/genres/edit.html.erb
<div class="mx-auto max-w-lg mt-10">
  <h1 class="font-bold text-4xl my-5">Editing genre</h1>
  <%= render "form", genre: @genre %>
</div>

app/views/genres/index.html.erb
<div class="max-w-7xl mx-auto py-10">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>
  <div class="flex">
    <div class="w-1/2 flex items-center">
      <h1 class="font-bold text-2xl">Genres</h1>
      <%= link_to new_genre_path, class: "flex items-center ml-5 block px-3 py-2 rounded bg-blue-500 hover:bg-blue-600 text-white" do %>
        <svg class="w-4 h-4 stroke-white mr-2" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="transparent" data-slot="icon">
          <path stroke-linecap="round" stroke-linejoin="round" d="M18 7.5v3m0 0v3m0-3h3m-3 0h-3m-2.25-4.125a3.375 3.375 0 1 1-6.75 0 3.375 3.375 0 0 1 6.75 0ZM3 19.235v-.11a6.375 6.375 0 0 1 12.75 0v.109A12.318 12.318 0 0 1 9.374 21c-2.331 0-4.512-.645-6.374-1.766Z" />
        </svg>
        Add genre
      <% end %>
    </div>
    <div class="w-1/2 flex items-center justify-end">
      <%= form_tag(genres_path, method: :get, class: "text-white min-w-[300px]") do %>
        <div class="relative">
          <%= text_field_tag(:search, params[:search],
                               placeholder: "Search genre...",
                               class: "w-full bg-zinc-700 py-2 px-3 rounded-lg focus:ring-white focus:border-white") %>
          <svg class="absolute top-[11px] right-3 w-5 h-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" >
            <path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z" />
          </svg>
        </div>
      <% end %>
    </div>
  </div>
  <div class="mt-5">
    <%= render "table" %>
  </div>
  <div class="flex items-center justify-center mt-5">
    <%= paginate @genres %>
  </div>
</div>

app/views/genres/new.html.erb
<div class="mx-auto max-w-lg mt-10">
  <h1 class="font-bold text-4xl my-5">New genre</h1>
  <%= render "form", genre: @genre %>
</div>

app/views/genres/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @genre %>

    <%= link_to "Edit this genre", edit_genre_path(@genre), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this genre", genre_path(@genre), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to genres", genres_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>