config/routes.rb
Rails.application.routes.draw do
  resources :genres
  resources :users
  resources :movies
  devise_for :users,
             path: "auth",
             path_names: {
               sign_in: "login",
               sign_out: "logout",
               sign_up: "register",
             }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "movies#index"
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze

  paginates_per 10
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable, :validatable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
  validates :name, presence: true, length: { maximum: 255 }

  validates_presence_of :email
  validates_uniqueness_of :email, allow_blank: true, case_sensitive: true
  validates_format_of :email, with: VALID_EMAIL_REGEX, allow_blank: true

  validates_presence_of :password, on: :create
  validates_confirmation_of :password, on: :create

  scope :with_filter, ->(search) {
          where("name like :search or email like :search", search: "%#{search}%") if search.present?
        }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.with_filter(params[:search])
      .order(id: :desc)
      .page(params[:page])
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      user_params.delete(:password) if user_params[:password].blank?
      if @user.update(user_params)
        format.html { redirect_to users_url, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, class: "contents") do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation" class="text-red-500 mb-5">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
    </div>
  <% end %>
  <div>
    <%= form.label :name, class: "after:content-['*'] after:ml-1 after:text-red-500 block" %>
    <%= form.text_field :name,
                            class: "mt-2 w-full bg-zinc-700 py-2 px-3 rounded-lg focus:ring-white focus:border-white",
                            placeholder: "Enter name" %>
    <% user.errors.full_messages_for(:name).each do |message| %>
      <div class="text-red-500 mt-2"><%= message %></div>
    <% end %>
  </div>
  <div class="mt-5">
    <%= form.label :email, class: "after:content-['*'] after:ml-1 after:text-red-500 block" %>
    <%= form.email_field :email,
                            class: "mt-2 w-full bg-zinc-700 py-2 px-3 rounded-lg focus:ring-white focus:border-white",
                            placeholder: "Enter email" %>
    <% user.errors.full_messages_for(:email).each do |message| %>
      <div class="text-red-500 mt-2"><%= message %></div>
    <% end %>
  </div>
  <div class="mt-5">
    <%= form.label :password, class: "after:content-['*'] after:ml-1 after:text-red-500 block" %>
    <%= form.password_field :password,
                            class: "mt-2 w-full bg-zinc-700 py-2 px-3 rounded-lg focus:ring-white focus:border-white",
                            placeholder: "Enter password" %>
    <% user.errors.full_messages_for(:password).each do |message| %>
      <div class="text-red-500 mt-2"><%= message %></div>
    <% end %>
  </div>
  <div class="w-full flex justify-end mt-5">
    <%= link_to "Cancel", users_path,
                  class: "py-2 px-3 bg-zinc-700 hover:bg-zinc-600 text-white rounded-lg mr-2" %>
    <%= form.submit(params[:action] == "new" ? "Create" : "Update", class: "cursor-pointer py-2 px-3 bg-blue-500 hover:bg-blue-600 text-white rounded-lg") %>
  </div>
<% end %>

app/views/users/_table.html.erb
<table class="min-w-full">
  <thead class="bg-zinc-700 border-b uppercase">
    <tr>
      <th scope="col" class="text-sm font-medium text-white px-6 py-4 text-left">
        ID
      </th>
      <th scope="col" class="text-sm font-medium text-white px-6 py-4 text-left">
        Name
      </th>
      <th scope="col" class="text-sm font-medium text-white px-6 py-4 text-left">
        Email
      </th>
      <th scope="col" class="text-sm font-medium text-white px-6 py-4 text-left">
        Created Date
      </th>
      <th scope="col" class="text-sm font-medium text-white px-6 py-4 text-left">
        Actions
      </th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr class="bg-transparent border-b transition duration-300 ease-in-out hover:bg-zinc-800">
        <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-white">
          <%= user.id %>
        </td>
        <td class="text-sm text-white font-light px-6 py-4 whitespace-nowrap">
          <%= user.name %>
        </td>
        <td class="text-sm text-white font-light px-6 py-4 whitespace-nowrap">
          <%= user.email %>
        </td>
        <td class="text-sm text-white font-light px-6 py-4 whitespace-nowrap">
          <%= Date.parse(user.created_at.to_s).strftime("%Y-%m-%d") %>
        </td>
        <td class="text-sm text-white font-light px-6 py-4 whitespace-nowrap">
          <%= link_to "Edit", edit_user_path(user), class: "px-3 py-2 rounded bg-zinc-700 hover:bg-zinc-600 text-white" %>
          <%= link_to "Delete", user, data: {
                      turbo_method: :delete,
                      turbo_confirm: "Are you sure?",
                    }, class: "ml-2 px-3 py-2 rounded bg-red-500 hover:bg-red-600 text-white" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <% if action_name != "show" %>
    <%= link_to "Show this user", user, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this user", edit_user_path(user), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="mx-auto max-w-lg mt-10">
  <h1 class="font-bold text-4xl my-5">Editing user</h1>
  <%= render "form", user: @user %>
</div>

app/views/users/index.html.erb
<div class="max-w-7xl mx-auto py-10">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>
  <div class="flex">
    <div class="w-1/2 flex items-center">
      <h1 class="font-bold text-2xl">Users</h1>
      <%= link_to new_user_path, class: "flex items-center ml-5 block px-3 py-2 rounded bg-blue-500 hover:bg-blue-600 text-white" do %>
        <svg class="w-4 h-4 stroke-white mr-2" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="transparent" data-slot="icon">
          <path stroke-linecap="round" stroke-linejoin="round" d="M18 7.5v3m0 0v3m0-3h3m-3 0h-3m-2.25-4.125a3.375 3.375 0 1 1-6.75 0 3.375 3.375 0 0 1 6.75 0ZM3 19.235v-.11a6.375 6.375 0 0 1 12.75 0v.109A12.318 12.318 0 0 1 9.374 21c-2.331 0-4.512-.645-6.374-1.766Z" />
        </svg>
        Add user
      <% end %>
    </div>
    <div class="w-1/2 flex items-center justify-end">
      <%= form_tag(users_path, method: :get, class: "text-white min-w-[300px]") do %>
        <div class="relative">
          <%= text_field_tag(:search, params[:search],
                               placeholder: "Search user...",
                               class: "w-full bg-zinc-700 py-2 px-3 rounded-lg focus:ring-white focus:border-white") %>
          <svg class="absolute top-[11px] right-3 w-5 h-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" >
            <path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z" />
          </svg>
        </div>
      <% end %>
      <%= link_to "#", class: "flex items-center ml-5 block px-3 py-2 rounded border border-blue-500 hover:bg-zinc-800 text-blue-500" do %>
        <svg class="w-4 h-5 mr-2" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" data-slot="icon">
          <path stroke-linecap="round" stroke-linejoin="round" d="M3 16.5v2.25A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75V16.5M16.5 12 12 16.5m0 0L7.5 12m4.5 4.5V3" />
        </svg>
        Import
      <% end %>
      <%= link_to "#", class: "flex items-center ml-5 block px-3 py-2 rounded bg-blue-500 hover:bg-blue-600 text-white" do %>
        <svg class="w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" data-slot="icon">
          <path stroke-linecap="round" stroke-linejoin="round" d="M3 16.5v2.25A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75V16.5m-13.5-9L12 3m0 0 4.5 4.5M12 3v13.5" />
        </svg>
        Export
      <% end %>
    </div>
  </div>
  <div class="mt-5">
    <%= render "table" %>
  </div>
  <div class="flex items-center justify-center mt-5">
    <%= paginate @users %>
  </div>
</div>

app/views/users/new.html.erb
<div class="mx-auto max-w-lg mt-10">
  <h1 class="font-bold text-4xl my-5">New user</h1>
  <%= render "form", user: @user %>
</div>

app/views/users/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @user %>

    <%= link_to "Edit this user", edit_user_path(@user), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this user", user_path(@user), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to users", users_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>