config/routes.rb
Rails.application.routes.draw do
  resources :genres
  resources :users
  resources :movies
  devise_for :users,
             path: "auth",
             path_names: {
               sign_in: "login",
               sign_out: "logout",
               sign_up: "register",
             }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "movies#index"
end

app/views/layouts/_footer.erb
<div class="max-w-7xl flex justify-between bg-zinc-700 mx-auto rounded-lg my-10 p-5">
    <div class="w-2/4 space-y-5">
        <div class="flex items-center space-x-2">
            <div>
                <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6" viewBox="0 0 28 28">
                    <path id="Exclusion_1" data-name="Exclusion 1" d="M18,28H5a5.006,5.006,0,0,1-5-5V10A10.011,10.011,0,0,1,10,0H23a5.006,5.006,0,0,1,5,5V18A10.011,10.011,0,0,1,18,28ZM10.621,8a1.16,1.16,0,0,0-.772.29,1.088,1.088,0,0,0-.35.832v9.753a1.122,1.122,0,0,0,1.7.968l8.251-4.875a1.124,1.124,0,0,0,0-1.936L11.2,8.153A1.13,1.13,0,0,0,10.621,8Z" fill="#fff"/>
                </svg>
            </div>
            <%= link_to "MTM Movie", root_path, class: "font-bold text-xl" %>
        </div>
        <p class="text-sm">Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum eaque facilis magni totam corporis obcaecati voluptatum id nesciunt ab pariatur quas voluptatem cum quos molestias molestiae corrupti, mollitia labore eum.</p>
    </div>
    <div class="w-1/4">
        <ul class="list-disc list-inside flex flex-col space-y-5">
            <li>
                <%= link_to "Terms and Conditions", "#" %>
            </li>
            <li>
                <%= link_to "Privacy Policy", "#" %>
            </li>
            <li>
                <%= link_to "FAQ", "#" %>
            </li>
        </ul>
    </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="bg-zinc-500 text-white bg-[url('/img/header.png')]">
  <div class="flex justify-between max-w-7xl mx-auto h-[160px] pt-[40px]">
    <!-- Logo & brand -->
    <div>
      <div class="flex items-center space-x-2 p-2">
        <div>
          <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6" viewBox="0 0 28 28">
            <path id="Exclusion_1" data-name="Exclusion 1" d="M18,28H5a5.006,5.006,0,0,1-5-5V10A10.011,10.011,0,0,1,10,0H23a5.006,5.006,0,0,1,5,5V18A10.011,10.011,0,0,1,18,28ZM10.621,8a1.16,1.16,0,0,0-.772.29,1.088,1.088,0,0,0-.35.832v9.753a1.122,1.122,0,0,0,1.7.968l8.251-4.875a1.124,1.124,0,0,0,0-1.936L11.2,8.153A1.13,1.13,0,0,0,10.621,8Z" fill="#fff"/>
          </svg>
        </div>
        <%= link_to "MTM Movie", root_path, class: "font-bold text-xl" %>
      </div>
    </div>
    <!-- Menu -->
    <div class="">
      <ul class="flex items-center space-x-5">
        <li class="hover:text-gray-300 <%= "border-b-2 border-white" if current_page?(root_path) || current_page?(movies_path) %>">
          <%= link_to "Movies", movies_path, class: "p-2" %>
        </li>
        <% if user_signed_in? %>
          <li class="hover:text-gray-300 <%= "border-b-2 border-white" if current_page?(new_movie_path) %>">
            <%= link_to "Add Movie", new_movie_path, class: "p-2" %>
          </li>
          <li class="hover:text-gray-300 <%= "border-b-2 border-white" if current_page?(genres_path) %>">
            <%= link_to "Genres", genres_path, class: "p-2" %>
          </li>
          <li class="hover:text-gray-300 <%= "border-b-2 border-white" if current_page?(users_path) %>">
            <%= link_to "Users", users_path, class: "p-2" %>
          </li>
          <li class="hover:text-gray-300">
            <button id="dropdownNavbarLink" class="flex items-center p-2">
              <%= current_user.name %>
              <svg class="w-2.5 h-2.5 ml-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/>
              </svg>
            </button>
            <!-- Dropdown menu -->
            <div id="dropdownNavbar" class="hidden absolute z-10 font-normal bg-zinc-700 text-white divide-y divide-gray-100 rounded-lg shadow w-44">
              <ul class="py-2 text-sm" aria-labelledby="dropdownLargeButton">
                <li>
                  <%= link_to "Profile", edit_user_registration_path, class: "block px-4 py-2 hover:bg-zinc-800" %>
                </li>
              </ul>
              <div class="py-1">
                <%= link_to "Logout",
                 destroy_user_session_path,
                  data: { turbo_method: :delete },
                  class: "block px-4 py-2 text-sm hover:bg-zinc-800"
                  %>
              </div>
            </div>
          </li>
        <% else %>
          <li class="hover:text-gray-300 <%= "border-b-2 border-white" if current_page?(new_user_session_path) %>">
            <%= link_to "Login", new_user_session_path %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMovie</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="bg-zinc-900 text-white">
    <%= render "layouts/navbar" %>
    <div class="min-h-[58vh]">
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>